##############################################
# +----------------------------------------+ #
# |            Item Update List            | #
# +----------------------------------------+ #
##############################################

update:

  # Toggle automatic updates of certain items if used.
  auto-update:
    armour: true

  "masterwork:masterwork_chestplate": "masterwork:masterwork_chestplate"
  "masterwork:masterwork_helmet": "masterwork:masterwork_helmet"

##############################################
# +----------------------------------------+ #
# |          Item configurations           | #
# +----------------------------------------+ #
##############################################

items:
  telekinetic-wand:
    blacklist:
      - CHEST
      - SHULKER
      - BARREL
      - FURNACE
      - DROPPER
      - DISPENSER
      - HOPPER
      - SMOKER
      - BREWING_STAND
      - DECORATED_POT
      - JUKEBOX
  architects-wand:
    CraftStair:
      - direction
      - half
      - stair_shape
      - waterlogged
    CraftWall:
      - wall_height
      - center
      - waterlogged
    CraftFence:
      - connection
      - waterlogged
    CraftIronBars:
      - connection
    CraftStainedGlassPane:
      - connection
    CraftLever:
      - direction
      - attachment
      - powered
    CraftTripWireHook:
      - direction
      - attached
      - powered
    CraftBed:
      - direction
      - bed_part
    CraftBigDripleaf:
      - dripleaf_tilt
      - direction
    CraftButton:
      - direction
      - powered
    CraftTrapDoor:
      - open
    CraftDoor:
      - open
  creeper_bow:
    tnt_chance: 0.15
    offset: 1
    velocity_multiplier: 2.0
    fuse-time: 
  creeper_rocket:
    refill-item: "dungeons:charged_gunpowder"
    max-usages: 256
    usages-per-refill: 4
  kraken-armour:
    cooldown: 60 # in seconds
    assistant-commands:
    - "mm test cast Kraken_Summon_Dead_Adventurer_Assistant"
    - "mm test cast Kraken_Summon_Tentacle_Assistant"
  kraken-sabre:
    lightning-chance: 1.0
    lightning-damage: 5
  banana-sabre:
    slip-chance: 1.0
    slip-strength: 5

##############################################
# +----------------------------------------+ #
# |                Vouchers                | #
# +----------------------------------------+ #
##############################################

# Section to edit values related to redeeming voucher items.

vouchers:
  # What ItemsAdder namespace are the vouchers kept in?
  namespace: "vouchers"
  # Item path must start with this (case-insensitive).
  # For example: vouchers:prefixbear
  path-prefix: "prefix"
  # How to build the permission from the derived key, this is what users are assigned after redeeming.
  # %key% is replaced after normalisation.
  permission-format: "chatprefix.%key%"
  # What particle should play when a prefix is successfully redeemed.
  # Leave empty for no particles.
  play-particle: "ENCHANT"
  # What sound should play when a prefix is successfully redeemed.
  # Leave empty for no sound.
  success-sound: "entity.experience_orb.pickup"
  # What sound should play if a prefix is unsuccessfully redeemed.
  # Leave empty for no sound.
  fail-sound: "entity.villager.no"

##############################################
# +----------------------------------------+ #
# |          Custom Potion Config          | #
# +----------------------------------------+ #
##############################################

# Here is where you can add new potion variants of VANILLA status effects.
# See the example block below on how to format the file.
# Please note that this plugin only supports ItemsAdder as a dependency, and uses their base items to apply effects.
# See below for a configuration explanation and some examples of potions of hunger.

# custom_potions:                   # Namespace of the item.
#   custom_drinkable_potion:        # Name of the item.
#     form: DRINK                   # Potion type, accepts DRINK, SPLASH, LINGERING.
#     effect: HUNGER                # Potion effect, accepts PotionEffectType from Paper API.
#     amplifier: 0                  # Severity of potion, 0 is regular strength - higher numbers are stronger.
#     duration: 24000               # Length of potion effect, in ticks. 20 ticks = 1 second.

potions:

  custom_potions:

    hunger1:
      form: DRINK
      effect: HUNGER
      amplifier: 0
      duration: 2400

    hunger2:
      form: DRINK
      effect: HUNGER
      amplifier: 1
      duration: 1200

    hunger3:
      form: DRINK
      effect: HUNGER
      amplifier: 0
      duration: 4800

    hunger4:
      form: SPLASH
      effect: HUNGER
      amplifier: 0
      duration: 2400

    hunger5:
      form: LINGERING
      effect: HUNGER
      amplifier: 0
      duration: 1200


##############################################
# +----------------------------------------+ #
# |                Language                | #
# +----------------------------------------+ #
##############################################

# This section has editable language configurations for plugin messages.

messages:
  prefix: "<bold><red>U</red><white>L</white> Dungeons <dark_gray>Â» </dark_gray></bold>"
  reload: "<dark_green>Plugin reloaded."
  tool-broken: "<red>This tool is broken and needs repair to continue using it.</red>"
  armour-broken: "<yellow>This armour is broken and you will take double damage until it is repaired.</yellow>"
  voucher-unlocked: "<green>Voucher successfully redeemed!</green>"
  voucher-owned: "<yellow>You have already redeemed this voucher!</yellow>"
  voucher-failed: "<red>Error with redeeming voucher. Please contact Staff.</red>"
  update-no-item: "<red>You must hold an item to update in your main hand.</red>"
  update-no-custom-item: "<red>This is not a custom item and can't be updated.</red>"
  update-updating: "<gray>Updating item...</gray>"
  update-enchants: "<gray>Adding enchants...</gray>"
  update-damage: "<gray>Applying damage...</gray>"
  update-trim: "<gray>Applying trim...</gray>"
  update-done: "<gray>Done.</gray>"
  update-error: "<red>This item can't be updated.</red>"
      